from __future__ import print_function

import pandas as pd


def RSI(prices, period=14):
    """
    Developed J. Welles Wilder, the Relative Strength Index (RSI) is a
    momentum oscillator that measures the speed and change of price
    movements. RSI oscillates between zero and 100. Traditionally,
    and according to Wilder, RSI is considered overbought when above 70
    and oversold when below 30. Signals can also be generated by looking
    for divergences, failure swings and centerline crossovers. RSI can
    also be used to identify the general trend.
    """
    df = prices.copy()
    df['diff'] = df['close'].diff().fillna(0.0)
    df['gain'] = df[df['diff'] > 0]['diff']
    df['gain'].fillna(0.0, inplace=True)
    df['loss'] = df[df['diff'] < 0]['diff'].abs()
    df['loss'].fillna(0.0, inplace=True)
    
    df['avg_gain'] = df['gain'].ewm(span=period+1).mean()
    df['avg_loss'] = df['loss'].ewm(span=period+1).mean()

    df['rs'] = df['avg_gain'] / df['avg_loss']
    df['rs'].fillna(0.0, inplace=True)
    rsi = 100. - (100. / (1 + df['rs']))
    
    return rsi
